"""empty message

Revision ID: 00becee0d7e8
Revises: 
Create Date: 2021-12-16 16:30:44.441981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00becee0d7e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_ibfk_1', 'card', type_='foreignkey')
    op.drop_column('card', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('user', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('card_ibfk_1', 'card', 'user', ['user'], ['id'])
    # ### end Alembic commands ###
