"""empty message

Revision ID: 880808fb54ef
Revises: 00becee0d7e8
Create Date: 2021-12-16 16:33:44.803937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880808fb54ef'
down_revision = '00becee0d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'user')
    # ### end Alembic commands ###
