"""empty message

Revision ID: a0b5ec786850
Revises: 425d088a6401
Create Date: 2021-12-16 16:40:09.837002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b5ec786850'
down_revision = '425d088a6401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'user')
    # ### end Alembic commands ###
