"""empty message

Revision ID: 7c043ffb86bd
Revises: 
Create Date: 2022-01-23 17:38:38.714620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c043ffb86bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('card_number', table_name='card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('card_number', 'card', ['card_number'], unique=False)
    # ### end Alembic commands ###
