"""empty message

Revision ID: 925a5bfd7cde
Revises: ddfd8f6de52d
Create Date: 2022-01-24 21:10:51.627840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925a5bfd7cde'
down_revision = 'ddfd8f6de52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('gas', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'gas')
    # ### end Alembic commands ###
