"""empty message

Revision ID: 96c2e5869c0f
Revises: 7c043ffb86bd
Create Date: 2022-01-23 19:05:24.837591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96c2e5869c0f'
down_revision = '7c043ffb86bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
