"""empty message

Revision ID: b822ecf469bc
Revises: 
Create Date: 2022-01-23 17:36:26.165498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b822ecf469bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('card_number', table_name='card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('card_number', 'card', ['card_number'], unique=False)
    # ### end Alembic commands ###
