export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const GET_CURRENT_USER_INFO_SUCCESS = "GET_DATA_SUCCESS";
export const GET_CURRENT_USER_INFO_FAIL = "GET_DATA_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const FILTER_TRANSACTIONS_SUCCESS = "FILTER_TRANSACTIONS_SUCCESS";
export const FILTER_TRANSACTIONS_FAIL = "FILTER_TRANSACTIONS_FAIL";
export const EDIT_SUCCESS = "EDIT_SUCCESS";
export const EDIT_FAIL = "EDIT_FAIL";

export const SENT_TRANSACTIONS_DATA_FETCH_FAIL =
  "SENT_TRANSACTIONS_DATA_FETCH_FAIL";
export const SENT_TRANSACTIONS_DATA_FETCH_SUCCESS =
  "SENT_TRANSACTIONS_DATA_FETCH_SUCCESS";
export const RECVD_TRANSACTIONS_DATA_FETCH_FAIL =
  "RECVD_TRANSACTIONS_DATA_FETCH_FAIL";
export const RECVD_TRANSACTIONS_DATA_FETCH_SUCCESS =
  "RECVD_TRANSACTIONS_DATA_FETCH_SUCCESS";
