"""empty message

Revision ID: 104097f7991e
Revises: b408facb94bd
Create Date: 2022-01-17 01:50:16.603512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '104097f7991e'
down_revision = 'b408facb94bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coin_ibfk_1', 'coin', type_='foreignkey')
    op.drop_column('coin', 'amount')
    op.drop_column('coin', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('coin', sa.Column('amount', mysql.FLOAT(), nullable=False))
    op.create_foreign_key('coin_ibfk_1', 'coin', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
