"""empty message

Revision ID: 491447cf455e
Revises: 03f26ab366e1
Create Date: 2021-12-16 18:55:38.372609

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '491447cf455e'
down_revision = '03f26ab366e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
