"""empty message

Revision ID: b408facb94bd
Revises: 7db789947201
Create Date: 2022-01-17 01:48:58.082928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b408facb94bd'
down_revision = '7db789947201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'amount')
    # ### end Alembic commands ###
